version: '3.8'

services:
  web:
    restart: always
    build: .
    ports:
      - "8001:8080"
    # depends_on:
    #   - db
    environment:
      - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=watch"
      - JWT_SECRET=6bc586e8db18e9b663f66b062bbb08509010e222fb2469d45009b68013ac430d
      - FIREBASE_FCM_URL=https://fcm.googleapis.com/fcm/send
      - FIREBASE_FCM_AUTH=key=AAAAP89u1s0:APA91bHf2dDH0XrJt1u71o8UrNsmOt57A4TJhQzj_MtSygfHoBJ_6VXvjriacwhcNeLSHp4Ix947YmtZO_f2IwJL_9zqU2UkKH6gSzbpJ86YXXghiCfLoLpJ9Iz4Hsj8SMQ8XhjrcAC1
      - PYVECFINDER_URL=http://pyvecfinder:5000
      - PLATFORM_REQUIRED_SIGNIN=none
      - DEMO_USER_ID=14
      - INSTANT_IO_URL=http://instantio:3000/instantio/emit
      - DEMO_PLATFORM=none
      - "VERSION_UPDATE_MESSAGE=New features and improvements await in the latest version of Watch Vault by Diggie! Update now for a better experience."
      - IOS_VERSION=1.0.30
      - ANDROID_VERSION=1.0.33
      - REPORT_FORGE_URL=http://webwand:3000/webwand/site-to-pdf
    volumes:
      - ./images:/images
      - ./products:/products
  pyvecfinder:
    restart: always
    image: htetlinmaung/pyvecfinder
    ports:
      - "5000:5000"
    volumes:
      - ./store:/usr/src/app/store
      - ./images:/usr/src/app/images
  instantio:
    restart: always
    image: htetlinmaung/instantio
    ports:
      - "8002:3000"
    environment:
      TOKEN_VERIFICATION_WEB_HOOK: "http://web:8080/api/auth/verify-token"
      INSTANTIO_WEB_HOOK: "http://web:8080/api/update-instantio-state"
      TZ: "Asia/Yangon"
      # SOCKETIO_NAMESPACES: "/pos"
  webwand:
    image: htetlinmaung/webwand
    restart: always
    ports:
      - "8004:3000"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ./images:/app/images
      - ./reports:/app/pdf
      - ./fonts:/usr/share/fonts/custom-fonts
  # report_forge:
  #   image: htetlinmaung/report_forge
  #   ports:
  #     - "8004:8080"
  #   environment:
  #     - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=report"
  #   volumes:
  #     - ./fonts:/usr/share/fonts/custom-fonts
  #     - ./templates:/templates
  #     - ./reports:/reports
  #     - ./images:/images

  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: