version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8080"
    # depends_on:
    #   - db
    environment:
      - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=watch"
      - JWT_SECRET=6bc586e8db18e9b663f66b062bbb08509010e222fb2469d45009b68013ac430d
    volumes:
      - ./images:/images

  # db:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: