const fs = require("fs");

const data = [
  "Alexandre Christie",
  "Armani Exchange",
  "Audemars Piguet",
  "Breitling",
  "Bulova",
  "Baby-G",
  "Bremont",
  "Blancpain",
  "Boucheron",
  "Citizen",
  "Casio",
  "Cartier",
  "Calvin Klein",
  "Casio Edifice",
  "Credor",
  "Diesel",
  "Dennis Martin",
  "Emporio Armani",
  "Edox",
  "esprit",
  "Fossil",
  "Frederique Constant",
  "Fortis",
  "Franck Muller",
  "Garmin",
  "Gucci",
  "Grand Seiko",
  "Guess",
  "G-Shock",
  "Gerald Charles",
  "Hamilton",
  "Hublot",
  "Heuer",
  "Harmes",
  "Invicta",
  "IWC",
  "Iron Annie",
  "Jacob & Co",
  "Jaeger-LeCoultre",
  "Junghans",
  "Kelek",
  "Konstantin Chaykin",
  "Louis Vuitton",
  "Luminox",
  "Lorus",
  "Longines",
  "Ludovic Ballouard",
  "Laco",
  "Michael Kors",
  "Marathon",
  "Maserati",
  "Montblanc",
  "Movado",
  "Mercury",
  "Mondaine",
  "Mido",
  "Marlboro",
  "Nomos",
  "Nivada",
  "Oris",
  "Orient",
  "Patek Philippe",
  "Pagani Design",
  "Panerai",
  "Puma",
  "Quinting",
  "Ratio",
  "Romanson",
  "Rado",
  "Rotary",
  "Richard Mille",
  "Seven Friday",
  "Swatch",
  "Steeldive",
  "Stowa",
  "Swiss Military",
  "Sugess",
  "Sea-Gull",
  "Tissot",
  "Thomas Earnshaw",
  "Timex",
  "Tudor",
  "Universal Geneve",
  "U-boat",
  "Vacheron Constant",
  "Victoria Swiss Army",
  "Versace",
  "Wakmann",
  "Werenbach",
  "Wyler",
  "Xemex",
  "Xetum",
  "Yema",
  "Zeppelin",
  "Zenith",
  "Zodiac",
];

fs.writeFileSync(
  "brand.sql",
  data
    .map(
      (b) =>
        `insert into brands (name, description, logo_url, creator_id) values ('${b}', '', '', 1);`
    )
    .join("\n")
);
